name: NNFun
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - blas
  - bzip2
  - ca-certificates
  - expat
  - intel-openmp
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libgomp
  - libstdcxx-ng
  - libuuid
  - mkl
  - mkl_fft
  - mkl_random
  - ncurses
  - numpy-base
  - openssl
  - python
  - readline
  - sqlite
  - tbb
  - tk
  - xz
  - zlib
  - pip:
    - absl-py
    - asttokens
    - certifi
    - charset-normalizer
    - comm
    - debugpy
    - decorator
    - dm-tree
    - executing
    - filelock
    - fsspec
    - h5py
    - idna
    - ipykernel
    - ipython
    - jedi
    - jinja2
    - jupyter-client
    - jupyter-core
    - markdown-it-py
    - markupsafe
    - matplotlib-inline
    - mdurl
    - mkl-fft
    - mkl-random
    - mkl-service
    - mpmath
    - namex
    - nest-asyncio
    - networkx
    - numpy
    - nvidia-cublas-cu12
    - nvidia-cuda-cupti-cu12
    - nvidia-cuda-nvrtc-cu12
    - nvidia-cuda-runtime-cu12
    - nvidia-cudnn-cu12
    - nvidia-cufft-cu12
    - nvidia-curand-cu12
    - nvidia-cusolver-cu12
    - nvidia-cusparse-cu12
    - nvidia-nccl-cu12
    - nvidia-nvjitlink-cu12
    - nvidia-nvtx-cu12
    - packaging
    - pandas
    - parso
    - pexpect
    - pillow
    - pip
    - platformdirs
    - prompt-toolkit
    - psutil
    - ptyprocess
    - pure-eval
    - pygments
    - python-dateutil
    - pytz
    - pyzmq
    - requests
    - rich
    - scipy
    - setuptools
    - six
    - stack-data
    - sympy
    - torch
    - torchaudio
    - torchvision
    - tornado
    - traitlets
    - triton
    - typing-extensions
    - tzdata
    - urllib3
    - wcwidth
    - wheel

